import type { NextPage } from "next";
import Head from "next/head";
import { prisma } from "../db/client";
import { trpc } from "../utils/trpc";

const Home: NextPage = (props: any) => {
  const { isLoading, data } = trpc.useQuery(["hello"]);
  if (isLoading || !data) <div>Loading...</div>;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="">
          <div>{data?.greeting}</div>
        </h1>
      </main>
    </div>
  );
};

export const getServerSideProps = async () => {
  const questions = await prisma.pollQuestion.findMany();

  return {
    props: {
      questions: JSON.stringify(questions, undefined, 2),
    },
  };
};

export default Home;
